"""
Pydantic models for type-safe trading engine.
Provides strict validation and serialization for all data structures.
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional, Literal
from enum import Enum
from pydantic import BaseModel, Field, field_validator


class SignalType(str, Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class OrderStatus(str, Enum):
    """Order execution status."""
    PENDING = "PENDING"
    EXECUTED = "EXECUTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class PriceTick(BaseModel):
    """Single price tick from WebSocket stream."""
    
    symbol: str = Field(..., description="Trading pair symbol (e.g., BTCUSDT)")
    price: Decimal = Field(..., gt=0, description="Current price")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Tick timestamp")
    volume: Optional[Decimal] = Field(None, ge=0, description="Trade volume")
    
    class Config:
        json_encoders = {
            Decimal: lambda v: float(v)
        }


class Candle(BaseModel):
    """OHLCV candlestick data."""
    
    symbol: str
    open_price: Decimal = Field(..., gt=0)
    high_price: Decimal = Field(..., gt=0)
    low_price: Decimal = Field(..., gt=0)
    close_price: Decimal = Field(..., gt=0)
    volume: Decimal = Field(..., ge=0)
    timestamp: datetime
    
    @field_validator('high_price', 'low_price')
    @classmethod
    def validate_high_low(cls, v: Decimal, info) -> Decimal:
        """Ensure high >= low."""
        if info.field_name == 'high_price' and 'low_price' in info.data:
            if v < info.data['low_price']:
                raise ValueError('high_price must be >= low_price')
        return v


class MovingAverageState(BaseModel):
    """Current state of moving average calculations."""
    
    symbol: str
    sma_short: Optional[Decimal] = Field(None, description="Short-period SMA")
    sma_long: Optional[Decimal] = Field(None, description="Long-period SMA")
    price: Decimal
    timestamp: datetime
    
    class Config:
        json_encoders = {
            Decimal: lambda v: float(v)
        }


class TradingSignal(BaseModel):
    """Trading signal generated by the engine."""
    
    symbol: str
    signal_type: SignalType
    price: Decimal = Field(..., gt=0)
    sma_short: Optional[Decimal] = None
    sma_long: Optional[Decimal] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0, description="Signal confidence 0-1")
    reason: str = Field(default="", description="Reason for signal")
    
    class Config:
        json_encoders = {
            Decimal: lambda v: float(v)
        }


class Order(BaseModel):
    """Execution order placed by the engine."""
    
    order_id: str
    symbol: str
    signal_id: Optional[str] = None
    signal_type: SignalType
    quantity: Decimal = Field(..., gt=0)
    entry_price: Decimal = Field(..., gt=0)
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    executed_at: Optional[datetime] = None
    execution_price: Optional[Decimal] = None
    notes: str = ""
    
    class Config:
        json_encoders = {
            Decimal: lambda v: float(v)
        }


class EngineConfig(BaseModel):
    """Trading engine configuration."""
    
    symbols: list[str] = Field(default=["BTCUSDT"], description="Trading pairs to monitor")
    sma_short_period: int = Field(default=10, ge=2)
    sma_long_period: int = Field(default=20, ge=2)
    db_url: str = Field(default="sqlite:///trading_engine.db")
    websocket_url: str = Field(
        default="wss://stream.binance.com:9443/ws",
        description="Binance WebSocket URL"
    )
    data_feed: Literal["binance", "alpaca"] = Field(default="binance")
    risk_management_enabled: bool = Field(default=True)
    position_size_percent: float = Field(default=1.0, ge=0.1, le=10.0)
    stop_loss_percent: float = Field(default=2.0, ge=0.5, le=10.0)
    take_profit_percent: float = Field(default=5.0, ge=1.0, le=50.0)


class PerformanceMetrics(BaseModel):
    """Engine performance and trading metrics."""
    
    total_signals: int = 0
    buy_signals: int = 0
    sell_signals: int = 0
    total_orders: int = 0
    executed_orders: int = 0
    failed_orders: int = 0
    total_pnl: Decimal = Field(default=Decimal(0), description="Total profit/loss")
    win_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    uptime_seconds: int = 0
    last_signal_time: Optional[datetime] = None
    
    class Config:
        json_encoders = {
            Decimal: lambda v: float(v)
        }
